### ISSUE TITLE
Emacs on mac fail to start: (void-function mac-auto-operator-composition-mode)

### ISSUE THREAD

**Issue by whjiang** [ztlevi/doom-config#1]
Debugger entered--Lisp error: (void-function mac-auto-operator-composition-mode)
  (mac-auto-operator-composition-mode)
  (progn (mac-auto-operator-composition-mode))
  (if IS-MAC (progn (mac-auto-operator-composition-mode)))
  eval-buffer(#<buffer  *load*-116622> nil "/Users/guobei/.doom.d/+ui.el" nil t)  ; Reading at buffer position 2657
  load-with-code-conversion("/Users/guobei/.doom.d/+ui.el" "/Users/guobei/.doom.d/+ui.el" nil nil)
  load("/Users/guobei/.doom.d/+ui" nil nil)
  (condition-case e (load (expand-file-name "+ui" "/Users/guobei/.doom.d/") nil nil) ((debug doom-error) (signal (car e) (cdr e))) ((debug error) (let* ((source (file-name-sans-extension (expand-file-name "+ui" "/Users/guobei/.doom.d/"))) (err (cond ((file-in-directory-p source doom-core-dir) (cons 'doom-error doom-core-dir)) ((file-in-directory-p source doom-private-dir) (cons 'doom-private-error doom-private-dir)) ((cons 'doom-module-error doom-emacs-dir))))) (signal (car err) (list (file-relative-name (concat source ".el") (cdr err)) e)))))
  eval-buffer(#<buffer  *load*-260269> nil "/Users/guobei/.doom.d/config.el" nil t)  ; Reading at buffer position 130
  load-with-code-conversion("/Users/guobei/.doom.d/config.el" "/Users/guobei/.doom.d/config.el" t nil)
  load("/Users/guobei/.doom.d/config" t nil)
  (condition-case e (load (expand-file-name "config" doom-private-dir) t nil) ((debug doom-error) (signal (car e) (cdr e))) ((debug error) (let* ((source (file-name-sans-extension (expand-file-name "config" doom-private-dir))) (err (cond ((file-in-directory-p source doom-core-dir) (cons 'doom-error doom-core-dir)) ((file-in-directory-p source doom-private-dir) (cons 'doom-private-error doom-private-dir)) ((cons 'doom-module-error doom-emacs-dir))))) (signal (car err) (list (file-relative-name (concat source ".el") (cdr err)) e)))))
  (if noninteractive nil (maphash (function (lambda (key plist) (let ((doom--current-module key) (doom--current-flags (plist-get plist :flags))) (condition-case e (load (expand-file-name "config" (plist-get plist :path)) t nil) ((debug doom-error) (signal (car e) (cdr e))) ((debug error) (let* ((source (file-name-sans-extension (expand-file-name "config" (plist-get plist :path)))) (err (cond ((file-in-directory-p source doom-core-dir) (cons 'doom-error doom-core-dir)) ((file-in-directory-p source doom-private-dir) (cons 'doom-private-error doom-private-dir)) ((cons 'doom-module-error doom-emacs-dir))))) (signal (car err) (list (file-relative-name (concat source ".el") (cdr err)) e)))))))) doom-modules) (run-hook-wrapped 'doom-init-modules-hook (function doom-try-run-hook)) (condition-case e (load (expand-file-name "config" doom-private-dir) t nil) ((debug doom-error) (signal (car e) (cdr e))) ((debug error) (let* ((source (file-name-sans-extension (expand-file-name "config" doom-private-dir))) (err (cond ((file-in-directory-p source doom-core-dir) (cons 'doom-error doom-core-dir)) ((file-in-directory-p source doom-private-dir) (cons 'doom-private-error doom-private-dir)) ((cons 'doom-module-error doom-emacs-dir))))) (signal (car err) (list (file-relative-name (concat source ".el") (cdr err)) e))))) (if custom-file nil (setq custom-file (concat doom-local-dir "custom.el"))) (if (stringp custom-file) (progn (load custom-file t t t))))
  (progn (setq doom-init-modules-p t) (maphash (function (lambda (key plist) (let ((doom--current-module key) (doom--current-flags (plist-get plist :flags))) (condition-case e (load (expand-file-name "init" (plist-get plist :path)) t nil) ((debug doom-error) (signal (car e) (cdr e))) ((debug error) (let* ((source (file-name-sans-extension (expand-file-name "init" (plist-get plist :path)))) (err (cond ((file-in-directory-p source doom-core-dir) (cons 'doom-error doom-core-dir)) ((file-in-directory-p source doom-private-dir) (cons 'doom-private-error doom-private-dir)) ((cons 'doom-module-error doom-emacs-dir))))) (signal (car err) (list (file-relative-name (concat source ".el") (cdr err)) e)))))))) doom-modules) (run-hook-wrapped 'doom-before-init-modules-hook (function doom-try-run-hook)) (if noninteractive nil (maphash (function (lambda (key plist) (let ((doom--current-module key) (doom--current-flags (plist-get plist :flags))) (condition-case e (load (expand-file-name "config" (plist-get plist :path)) t nil) ((debug doom-error) (signal (car e) (cdr e))) ((debug error) (let* ((source (file-name-sans-extension (expand-file-name "config" (plist-get plist :path)))) (err (cond ((file-in-directory-p source doom-core-dir) (cons 'doom-error doom-core-dir)) ((file-in-directory-p source doom-private-dir) (cons 'doom-private-error doom-private-dir)) ((cons 'doom-module-error doom-emacs-dir))))) (signal (car err) (list (file-relative-name (concat source ".el") (cdr err)) e)))))))) doom-modules) (run-hook-wrapped 'doom-init-modules-hook (function doom-try-run-hook)) (condition-case e (load (expand-file-name "config" doom-private-dir) t nil) ((debug doom-error) (signal (car e) (cdr e))) ((debug error) (let* ((source (file-name-sans-extension (expand-file-name "config" doom-private-dir))) (err (cond ((file-in-directory-p source doom-core-dir) (cons 'doom-error doom-core-dir)) ((file-in-directory-p source doom-private-dir) (cons 'doom-private-error doom-private-dir)) ((cons 'doom-module-error doom-emacs-dir))))) (signal (car err) (list (file-relative-name (concat source ".el") (cdr err)) e))))) (if custom-file nil (setq custom-file (concat doom-local-dir "custom.el"))) (if (stringp custom-file) (progn (load custom-file t t t)))))
  (if (and (or force-p (not doom-init-modules-p)) (not (setq doom-modules nil)) (condition-case e (load (expand-file-name "init" doom-private-dir) t nil) ((debug doom-error) (signal (car e) (cdr e))) ((debug error) (let* ((source (file-name-sans-extension (expand-file-name "init" doom-private-dir))) (err (cond ((file-in-directory-p source doom-core-dir) (cons 'doom-error doom-core-dir)) ((file-in-directory-p source doom-private-dir) (cons 'doom-private-error doom-private-dir)) ((cons 'doom-module-error doom-emacs-dir))))) (signal (car err) (list (file-relative-name (concat source ".el") (cdr err)) e)))))) (progn (setq doom-init-modules-p t) (maphash (function (lambda (key plist) (let ((doom--current-module key) (doom--current-flags (plist-get plist :flags))) (condition-case e (load (expand-file-name "init" (plist-get plist :path)) t nil) ((debug doom-error) (signal (car e) (cdr e))) ((debug error) (let* ((source (file-name-sans-extension (expand-file-name "init" (plist-get plist :path)))) (err (cond ((file-in-directory-p source doom-core-dir) (cons 'doom-error doom-core-dir)) ((file-in-directory-p source doom-private-dir) (cons 'doom-private-error doom-private-dir)) ((cons 'doom-module-error doom-emacs-dir))))) (signal (car err) (list (file-relative-name (concat source ".el") (cdr err)) e)))))))) doom-modules) (run-hook-wrapped 'doom-before-init-modules-hook (function doom-try-run-hook)) (if noninteractive nil (maphash (function (lambda (key plist) (let ((doom--current-module key) (doom--current-flags (plist-get plist :flags))) (condition-case e (load (expand-file-name "config" (plist-get plist :path)) t nil) ((debug doom-error) (signal (car e) (cdr e))) ((debug error) (let* ((source (file-name-sans-extension (expand-file-name "config" (plist-get plist :path)))) (err (cond ((file-in-directory-p source doom-core-dir) (cons 'doom-error doom-core-dir)) ((file-in-directory-p source doom-private-dir) (cons 'doom-private-error doom-private-dir)) ((cons 'doom-module-error doom-emacs-dir))))) (signal (car err) (list (file-relative-name (concat source ".el") (cdr err)) e)))))))) doom-modules) (run-hook-wrapped 'doom-init-modules-hook (function doom-try-run-hook)) (condition-case e (load (expand-file-name "config" doom-private-dir) t nil) ((debug doom-error) (signal (car e) (cdr e))) ((debug error) (let* ((source (file-name-sans-extension (expand-file-name "config" doom-private-dir))) (err (cond ((file-in-directory-p source doom-core-dir) (cons 'doom-error doom-core-dir)) ((file-in-directory-p source doom-private-dir) (cons 'doom-private-error doom-private-dir)) ((cons 'doom-module-error doom-emacs-dir))))) (signal (car err) (list (file-relative-name (concat source ".el") (cdr err)) e))))) (if custom-file nil (setq custom-file (concat doom-local-dir "custom.el"))) (if (stringp custom-file) (progn (load custom-file t t t))))))
  doom-initialize-modules()
  (if noninteractive nil (doom-initialize-modules))
  eval-buffer(#<buffer  *load*-992991> nil "/Users/guobei/.emacs.d/core/core.el" nil t)  ; Reading at buffer position 19926
  load-with-code-conversion("/Users/guobei/.emacs.d/core/core.el" "/Users/guobei/.emacs.d/core/core.el" nil t)
  require(core "/Users/guobei/.emacs.d/core/core")
  eval-buffer(#<buffer  *load*> nil "/Users/guobei/.emacs.d/init.el" nil t)  ; Reading at buffer position 3804
  load-with-code-conversion("/Users/guobei/.emacs.d/init.el" "/Users/guobei/.emacs.d/init.el" t t)
  load("/Users/guobei/.emacs.d/init" t t)
  #f(compiled-function () #<bytecode 0x400bef39>)()
  command-line()
  normal-top-level()

**Comment by whjiang** [comment]
seems this issue is caused by a specific function from emacs-mac. 

I tried to install emacs-mac according to the guide, but failed. It seems emacs-mac in homebrew is broken due to a dirty build. So, I disabled +ui and this issue gone.

**Comment by ztlevi** [comment]
You can simply remove the lines [here](https://github.com/ztlevi/doom-config/blob/master/+ui.el#L53-L56). It's for ligature support for font like `fira code`.

Not sure why emacs-mac build fails. Did u install with cask or build from stratch?
