### ISSUE TITLE
SPC-p-/ (+ivy/projectile-find-file) find file does NOT ignore .ccls-cache files

### ISSUE THREAD

**Issue by whjiang** [ztlevi/doom-config#2]
I use SPC-p-/ to find files in a project, which is a c++ project with ccls indexed. Alll the indexes are in .ccls-cache folder of project root. 

SPC-p-/ does NOT ignore these index files which makes the search ui quite ugly and error prone to select the right file.

**Comment by ztlevi** [comment]
I use `counsel-git` to find files. It's mapped to `M-p`. It will ignore git ignored files which works perfect. 

If u want to ignore it locally, put `.ccls-cache` in your projects's `.gitignore`.

While, if you prefer universally, you can find the clue [here](https://github.com/ztlevi/Dotfiles/blob/master/Home/.gitignore_global#L43). Also, you need to set `~/.gitconfig` like [this](https://github.com/ztlevi/Dotfiles/blob/master/Home_Linux/.gitconfig#L37).

Besides, I also map `SPC / h` to `+ivy/project-search-with-hidden-files` for searching including dot files.
