### ISSUE TITLE
Ubuntu配置显示乱码

### ISSUE THREAD

**Issue by hjhsggy** [ztlevi/doom-config#6]
使用楼主的配置完emacs之后打开界面显示乱码

**Comment by ztlevi** [comment]
看一下你有任意一个字体吗，https://github.com/ztlevi/doom-config/blob/master/%2Bui.el#L9

不确定你的乱码是文字全部乱码还是icon，如果只有icon，执行M-x all-the-icons-install-fonts

**Comment by hjhsggy** [comment]
thanks, 我的Ubuntu缺少"Operator Mono"这个字体,问题已解决

**Comment by ztlevi** [comment]
奇怪诶，你我应该加了两个fallback的字体，你系统里也都没有吗？
