### ISSUE TITLE
c/c++ dap-mode 用不起来

### ISSUE THREAD

**Issue by nehcuh** [ztlevi/doom-config#8]
c/c++ 的 dap-mode 用不起来，python 的 dap-mode 倒是正常的
已经配置了 ccls，也在 .emacs.d 下面安装了 lldb, 是还需要什么其他配置么？
我的系统是 macos catalina，指定的c/c++ 编译器是 clang-10
<img width="765" alt="001" src="https://user-images.githubusercontent.com/36597254/97654311-9a8c3680-1a9d-11eb-9e73-4e7ed0a7a0a6.png">

**Comment by ztlevi** [comment]
我也没试过c++用dap-mode，这个最好到emacs-china里问，看有没有人用。

估计大多数大佬还是不会用emacs去debug，很多直接撸gdb或者pdb这样。我之前也折腾了一段时间的dap-mode，后面发现要attach到docker里的running debugger还是有点难，没配成功。所以现在还一直是用pdb++。

**Comment by nehcuh** [comment]
En, 试了下spacemacs，一样没配置成功，哎……只能看着别人的截图心痒痒了
